"""Add location tracking columns to user table

Revision ID: 2d3899a99b54
Revises: 5cdc421d4965
Create Date: 2026-02-15 20:25:33.833861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3899a99b54'
down_revision = '5cdc421d4965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('real_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('real_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('real_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('real_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('real_region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_discrepancy', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('location_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('suspension_end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('suspension_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('suspension_duration', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('suspension_duration')
        batch_op.drop_column('suspension_reason')
        batch_op.drop_column('suspension_end_date')
        batch_op.drop_column('location_verified_at')
        batch_op.drop_column('location_discrepancy')
        batch_op.drop_column('real_region')
        batch_op.drop_column('real_country')
        batch_op.drop_column('real_city')
        batch_op.drop_column('real_longitude')
        batch_op.drop_column('real_latitude')
        batch_op.drop_column('real_ip')

    # ### end Alembic commands ###
